
#obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXTS) += mxt.o
#mxt-objs := atmel_mxt_ts.o plugin_cal.o plugin_ac.o plugin_proci.o plugin_misc.o plugin_clip.o plugin_wdg.o
#mxt-objs := atmel_mxt_ts.o plugin_cal.o plugin_ac.o plugin_proci.o plugin_misc.o plugin_clip.o
#mxt-objs := atmel_mxt_ts.o plugin_cal.o plugin_ac.o plugin_proci.o
#mxt-objs := atmel_mxt_ts.o plugin_proci.o plugin_clip.o  
#mxt-objs := atmel_mxt_ts.o plugin_cal.o plugin_ac.o
#mxt-objs := atmel_mxt_ts.o plugin_cal.o  
#mxt-objs := atmel_mxt_ts.o plugin_ac.o  
#mxt-objs := atmel_mxt_ts.o plugin_proci.o  
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXTS) += atmel_mxt_ts.o plugin_misc.o  plugin_ac.o plugin_cal.o plugin_clip.o plugin_proci.o plugin_wdg.o
#mxt-objs := atmel_mxt_ts.o plugin_clip.o  
#mxt-objs := atmel_mxt_ts.o plugin_wdg.o  
#mxt-objs := atmel_mxt_ts.o  

ifeq ($(CONFIG_TOUCHSCREEN_ATMEL_MXTS),y)
#CFLAGS_atmel_mxt_ts.o += -DDEBUG
endif
