obj-$(CONFIG_TOUCHSCREEN_TP_INFO) += lct_tp_fm_info.o
obj-$(CONFIG_TOUCHSCREEN_TP_INFO) += lct_ctp_selftest.o
obj-$(CONFIG_TOUCHSCREEN_TP_INFO) += lct_ctp_upgrade.o
obj-$(CONFIG_TOUCHSCREEN_TP_INFO) += lct_if_ctp_upgrade.o
